import type { Metadata } from "next";
import "./globals.css";
import RootLayout from "@repo/ui/components/layout/RootLayout";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return <RootLayout>{children}</RootLayout>;
}
